In [ ]:
!pip install git+https://github.com/huggingface/transformers.git -q

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for transformers (pyproject.toml) ... done

In [ ]:
!pip install torch tensorboard
!pip install datasets accelerate evaluate bitsandbytes trl peft protobuf sentencepiece huggingface_hub scipy einops

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.2)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorboard) (26.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (5.29.6)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (3.1.8)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting trl
  Downloading trl-1.2.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (5.29.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.10.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (0.8.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.6.0.dev0)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.2)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.5 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.6 MB/s eta 0:00:00
Downloading trl-1.2.0-py3-none-any.whl (697 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 697.4/697.4 kB 24.2 MB/s eta 0:00:00
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 34.7 MB/s eta 0:00:00
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 12.1 MB/s eta 0:00:00
Installing collected packages: pyarrow, bitsandbytes, datasets, evaluate, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed bitsandbytes-0.49.2 datasets-4.8.4 evaluate-0.4.6 pyarrow-23.0.1 trl-1.2.0

In [ ]:
import os
import json
import urllib.request
from typing import Dict, List, Optional
import torch
from datasets import Dataset
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda

In [ ]:
token = os.environ.get("HF_TOKEN")
login(token=token)

In [ ]:
MODEL_NAME = "google/gemma-4-E2B-it"
DATA_URL = "https://raw.githubusercontent.com/tangqiaoyu/ToolAlpaca/main/data/train_data.json"

In [ ]:
LORA_R = 4
LORA_ALPHA = 8
LORA_DROPOUT = 0.05
MAX_SEQ_LEN = 256
TRAIN_BATCH = 2
GRAD_ACCUM = 8
LR = 1e-4
NUM_EPOCHS = 2
MAX_TRAIN_STEPS = 500

In [ ]:
def download_json(url, local_path):
    if not os.path.exists(local_path):
        os.makedirs(os.path.dirname(local_path), exist_ok=True)
        urllib.request.urlretrieve(url, local_path)

    with open(local_path, "r", encoding="utf-8") as f:
        return json.load(f)

In [ ]:
DATA_PATH = "/content/train_data.json"
raw_train = download_json(DATA_URL, DATA_PATH)

In [ ]:
raw_train[0]

{'Name': 'Httpbin',
 'Description': 'A Simple HTTP Request & Response Service',
 'Link': 'https://httpbin.org/',
 'Category': 'Development',
 'Introduction': "The Httpbin API (Application Programming Interface) is a simple HTTP request and response service that enables developers to test their applications' interactions with the HTTP protocol. Httpbin provides the following functions: 1) Basic GET, POST, PUT, DELETE, HEAD, and PATCH http request testing. 2) Retrieval of client request data, including headers, form data, uploaded files, and cookies. 3) Endpoint for proxy headers testing. 4) Ability to simulate status codes and other responses. Httpbin is an easy-to-use, efficient, and reliable tool for testing and debugging HTTP-related issues in web and mobile applications.",
 'Functions': '1. Name: sendHttpRequest\nDescription: Send an HTTP request with the specified method, headers, and data to the Httpbin API for testing purposes.\nInput: {"method": "Required. String. The HTTP method to use (GET, POST, PUT, DELETE, HEAD, or PATCH)", "url": "Required. String. The endpoint URL to send the request to", "headers": "Optional. Object. A key-value pair of headers to include in the request", "data": "Optional. Object. A key-value pair of data to include in the request body"}\nOutput: {"response": "Object. The HTTP response received from the Httpbin API, including status code, headers, and body"}\n\n2. Name: getClientRequestData\nDescription: Retrieve the client\'s request data, including headers, form data, uploaded files, and cookies.\nInput: {"url": "Required. String. The endpoint URL to send the request to"}\nOutput: {"requestData": "Object. The client\'s request data, including headers, form data, uploaded files, and cookies"}\n\n3. Name: testProxyHeaders\nDescription: Send a request to the Httpbin API\'s proxy headers testing endpoint.\nInput: {"url": "Required. String. The endpoint URL to send the request to", "headers": "Optional. Object. A key-value pair of headers to include in the request"}\nOutput: {"response": "Object. The HTTP response received from the Httpbin API, including status code, headers, and body"}\n\n4. Name: simulateStatusCode\nDescription: Send a request to the Httpbin API\'s status code simulation endpoint to test how your application handles specific status codes.\nInput: {"url": "Required. String. The endpoint URL to send the request to", "statusCode": "Required. Integer. The HTTP status code to simulate"}\nOutput: {"response": "Object. The HTTP response received from the Httpbin API, including the simulated status code, headers, and body"}',
 'Documentation': '{"openapi": "3.0.0", "info": {"title": "Httpbin", "version": "1.0.0", "description": "A Simple HTTP Request & Response Service"}, "paths": {"/sendHttpRequest": {"post": {"operationId": "sendHttpRequest", "description": "Send an HTTP request with the specified method, headers, and data to the Httpbin API for testing purposes.", "parameters": [{"name": "method", "in": "query", "description": "The HTTP method to use (GET, POST, PUT, DELETE, HEAD, or PATCH)", "required": true, "schema": {"type": "string", "enum": ["GET", "POST", "PUT", "DELETE", "HEAD", "PATCH"]}}, {"name": "url", "in": "query", "description": "The endpoint URL to send the request to", "required": true, "schema": {"type": "string"}}, {"name": "headers", "in": "query", "description": "A key-value pair of headers to include in the request", "required": false, "schema": {"type": "object"}}, {"name": "data", "in": "query", "description": "A key-value pair of data to include in the request body", "required": false, "schema": {"type": "object"}}], "requestBody": {"description": "The HTTP request body", "required": false, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"200": {"description": "Successful response", "content": {"application/json": {"schema": {"type": "object", "properties": {"response": {"type": "object", "properties": {"status_code": {"type": "integer"}, "headers": {"type": "object"}, "body": {"type": "string"}}}}}}}}}}}, "/getClientRequestData": {"get": {"operationId": "getClientRequestData", "description": "Retrieve the client\'s request data, including headers, form data, uploaded files, and cookies.", "parameters": [{"name": "url", "in": "query", "description": "The endpoint URL to send the request to", "required": true, "schema": {"type": "string"}}], "responses": {"200": {"description": "Successful response", "content": {"application/json": {"schema": {"type": "object", "properties": {"requestData": {"type": "object", "properties": {"headers": {"type": "object"}, "form": {"type": "object"}, "files": {"type": "object"}, "cookies": {"type": "object"}}}}}}}}}}}, "/testProxyHeaders": {"post": {"operationId": "testProxyHeaders", "description": "Send a request to the Httpbin API\'s proxy headers testing endpoint.", "parameters": [{"name": "url", "in": "query", "description": "The endpoint URL to send the request to", "required": true, "schema": {"type": "string"}}, {"name": "headers", "in": "query", "description": "A key-value pair of headers to include in the request", "required": false, "schema": {"type": "object"}}], "requestBody": {"description": "The HTTP request body", "required": false, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"200": {"description": "Successful response", "content": {"application/json": {"schema": {"type": "object", "properties": {"response": {"type": "object", "properties": {"status_code": {"type": "integer"}, "headers": {"type": "object"}, "body": {"type": "string"}}}}}}}}}}}, "/simulateStatusCode": {"post": {"operationId": "simulateStatusCode", "description": "Send a request to the Httpbin API\'s status code simulation endpoint to test how your application handles specific status codes.", "parameters": [{"name": "url", "in": "query", "description": "The endpoint URL to send the request to", "required": true, "schema": {"type": "string"}}, {"name": "statusCode", "in": "query", "description": "The HTTP status code to simulate", "required": true, "schema": {"type": "integer"}}], "requestBody": {"description": "The HTTP request body", "required": false, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"200": {"description": "Successful response", "content": {"application/json": {"schema": {"type": "object", "properties": {"response": {"type": "object", "properties": {"status_code": {"type": "integer"}, "headers": {"type": "object"}, "body": {"type": "string"}}}}}}}}}}}}, "servers": [{"url": "https://httpbin.org/"}]}',
 'NLDocumentation': 'sendHttpRequest: Send an HTTP request with the specified method, headers, and data to the Httpbin API for testing purposes.\nParameters: {"method": "Required. string. One of: [GET, POST, PUT, DELETE, HEAD, PATCH]. The HTTP method to use (GET, POST, PUT, DELETE, HEAD, or PATCH).", "url": "Required. string. The endpoint URL to send the request to.", "headers": "Object.  A key-value pair of headers to include in the request.", "data": "Object.  A key-value pair of data to include in the request body."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{response: Object{status_code, headers: Object, body}}\ngetClientRequestData: Retrieve the client\'s request data, including headers, form data, uploaded files, and cookies.\nParameters: {"url": "Required. string. The endpoint URL to send the request to."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{requestData: Object{headers: Object, form: Object, files: Object, cookies: Object}}\ntestProxyHeaders: Send a request to the Httpbin API\'s proxy headers testing endpoint.\nParameters: {"url": "Required. string. The endpoint URL to send the request to.", "headers": "Object.  A key-value pair of headers to include in the request."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{response: Object{status_code, headers: Object, body}}\nsimulateStatusCode: Send a request to the Httpbin API\'s status code simulation endpoint to test how your application handles specific status codes.\nParameters: {"url": "Required. string. The endpoint URL to send the request to.", "statusCode": "Required. integer. The HTTP status code to simulate."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{response: Object{status_code, headers: Object, body}}\n',
 'Function_Description': {'sendHttpRequest': 'Send an HTTP request with the specified method, headers, and data to the Httpbin API for testing purposes.\nParameters: {"method": "Required. string. One of: [GET, POST, PUT, DELETE, HEAD, PATCH]. The HTTP method to use (GET, POST, PUT, DELETE, HEAD, or PATCH).", "url": "Required. string. The endpoint URL to send the request to.", "headers": "Object.  A key-value pair of headers to include in the request.", "data": "Object.  A key-value pair of data to include in the request body."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{response: Object{status_code, headers: Object, body}}',
  'getClientRequestData': 'Retrieve the client\'s request data, including headers, form data, uploaded files, and cookies.\nParameters: {"url": "Required. string. The endpoint URL to send the request to."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{requestData: Object{headers: Object, form: Object, files: Object, cookies: Object}}',
  'testProxyHeaders': 'Send a request to the Httpbin API\'s proxy headers testing endpoint.\nParameters: {"url": "Required. string. The endpoint URL to send the request to.", "headers": "Object.  A key-value pair of headers to include in the request."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{response: Object{status_code, headers: Object, body}}',
  'simulateStatusCode': 'Send a request to the Httpbin API\'s status code simulation endpoint to test how your application handles specific status codes.\nParameters: {"url": "Required. string. The endpoint URL to send the request to.", "statusCode": "Required. integer. The HTTP status code to simulate."}\nOutput: Successful response.\n - Format: application/json\n - Structure: Object{response: Object{status_code, headers: Object, body}}',
  'components': ''},
 'Function_Projection': {'sendHttpRequest': ['/sendHttpRequest', 'post'],
  'getClientRequestData': ['/getClientRequestData', 'get'],
  'testProxyHeaders': ['/testProxyHeaders', 'post'],
  'simulateStatusCode': ['/simulateStatusCode', 'post']},
 'Instructions': ['I\'m troubleshooting some requests, so can you help me send a POST request to https://httpbin.org/post with the header "Content-Type: application/json" and the data \'{"name": "John Doe", "email": "john.doe@example.com"}\'? Let me know the response details.',
  "Could you send a GET request to the following URL to retrieve my request information: https://httpbin.org/get? I'd like to see the details of my headers, cookies, and other request data.",
  'I have a feeling that some proxy headers aren\'t being passed correctly. Can you send a request to https://httpbin.org/headers with the headers "X-Forwarded-For: 192.168.1.1" and "X-Real-IP: 10.0.0.1"? I\'d like to verify if the headers are properly forwarded by the proxy.',
  "I'd like to see how my application responds to a 404 status code. Please send a request to https://httpbin.org/status/404 and let me know the details of the received status code and response headers.",
  'I need to test how my app handles a "PATCH" request. Can you send a PATCH request to https://httpbin.org/patch with the data \'{"field": "value"}\' and tell me the response?',
  "Let's find out if my request headers are being sent correctly. Send a request to https://httpbin.org/get and return the information about the headers' values I sent.",
  "I'd like to see how my app deals with a 503 Service Unavailable error. Send a request to https://httpbin.org/status/503 so that I can observe my application's behavior.",
  "Would you mind sending a DELETE request to https://httpbin.org/delete and telling me the response status code and headers? I'm checking if my app processes this method appropriately.",
  "I need to test my app's behavior when receiving cookies. Can you send a GET request to https://httpbin.org/cookies/set?sessionid=1234567890abcde and then retrieve the cookie data by sending another GET request to https://httpbin.org/cookies?",
  'I want to see if my app can properly handle a "HEAD" request. Can you send a HEAD request to https://httpbin.org/head and give me the details of the response headers?'],
 'Instances': [{'input': 'I\'m troubleshooting some requests, so can you help me send a POST request to https://httpbin.org/post with the header "Content-Type: application/json" and the data \'{"name": "John Doe", "email": "john.doe@example.com"}\'? Let me know the response details.',
   'output': 'The POST request was successful and the response contains the data sent in the request. The response status code was 200.',
   'Final Thought': 'The request was successful and the response contains the data sent in the request.',
   'intermediate_steps': [[['sendHttpRequest',
      '{"method": "POST", "url": "https://httpbin.org/post", "headers": {"Content-Type": "application/json"}, "data": {"name": "John Doe", "email": "john.doe@example.com"}}',
      ' I need to use the sendHttpRequest tool to send the POST request.\nAction: sendHttpRequest\nAction Input: {"method": "POST", "url": "https://httpbin.org/post", "headers": {"Content-Type": "application/json"}, "data": {"name": "John Doe", "email": "john.doe@example.com"}}'],
     'Status Code: 200. Response: {"response":{"status_code":200,"headers":{"Content-Type":"application/json"},"body":"{\\"args\\":{\\"method\\":\\"POST\\",\\"url\\":\\"https://httpbin.org/post\\",\\"headers\\":{\\"\'Content-Type\'\\":\\"\'application/json\'\\"},\\"data\\":{\\"\'name\'\\":\\"\'John Doe\'\\",\\"\'email\'\\":\\"\'john.doe@example.com\'\\"}},\\"data\\":\\"\\",\\"files\\":{},\\"form\\":{},\\"headers\\":{\\"Accept\\":\\"*/*\\",\\"Content-Length\\":\\"48\\",\\"Content-Type\\":\\"application/x-www-form-urlencoded\\",\\"Host\\":\\"httpbin.org\\",\\"User-Agent\\":\\"curl/7.68.0\\"},\\"json\\":{\\"\'name\'\\":\\"\'John Doe\'\\",\\"\'email\'\\":\\"\'john.doe@example.com\'\\"},\\"method\\":\\"POST\\",\\"origin\\":\\"127.0.0.1\\",\\"url\\":\\"https://httpbin.org/post\\"}"}}']]},
  {'input': "Could you send a GET request to the following URL to retrieve my request information: https://httpbin.org/get? I'd like to see the details of my headers, cookies, and other request data.",
   'output': 'Yes, I can send a GET request to the URL you provided to retrieve your request information. The response contains the following data: headers, form data, uploaded files, and cookies.',
   'Final Thought': "The response contains the user's request data, including headers, form data, uploaded files, and cookies.",
   'intermediate_steps': [[['getClientRequestData',
      '{"url": "https://httpbin.org/get"}',
      ' I need to use the getClientRequestData tool to retrieve the user\'s request data.\nAction: getClientRequestData\nAction Input: {"url": "https://httpbin.org/get"}'],
     'Status Code: 200. Response: {"requestData":{"headers":{"Accept":"*/*","User-Agent":"curl/7.58.0","Host":"httpbin.org"},"form":{},"files":{},"cookies":{}}}']]},
  {'input': 'I have a feeling that some proxy headers aren\'t being passed correctly. Can you send a request to https://httpbin.org/headers with the headers "X-Forwarded-For: 192.168.1.1" and "X-Real-IP: 10.0.0.1"? I\'d like to verify if the headers are properly forwarded by the proxy.',
   'output': 'The request was successful and the response body contains the headers that were sent in the request, including the X-Forwarded-For and X-Real-IP headers. This indicates that the proxy is properly forwarding the headers.',
   'Final Thought': 'The response status code is 200, which indicates that the request was successful. The response body contains the headers that were sent in the request, including the X-Forwarded-For and X-Real-IP headers. This indicates that the proxy is properly forwarding the headers.',
   'intermediate_steps': [[['sendHttpRequest',
      '{"method": "GET", "url": "https://httpbin.org/headers", "headers": {"X-Forwarded-For": "192.168.1.1", "X-Real-IP": "10.0.0.1"}}',
      ' I need to send an HTTP request with the specified headers to the given URL.\nAction: sendHttpRequest\nAction Input: {"method": "GET", "url": "https://httpbin.org/headers", "headers": {"X-Forwarded-For": "192.168.1.1", "X-Real-IP": "10.0.0.1"}}'],
     'Status Code: 200. Response: {"response":{"status_code":200,"headers":{"Content-Type":"application/json","X-Forwarded-For":"192.168.1.1","X-Real-IP":"10.0.0.1"},"body":"{\\n  \\"headers\\": {\\n    \\"Accept\\": \\"*/*\\",\\n    \\"Host\\": \\"httpbin.org\\",\\n    \\"User-Agent\\": \\"curl/7.68.0\\",\\n    \\"X-Amzn-Trace-Id\\": \\"Root=1-61101b75-4662aa436dc5e0161042d0f2\\"\\n  }\\n}\\n"}}']]},
  {'input': "I'd like to see how my application responds to a 404 status code. Please send a request to https://httpbin.org/status/404 and let me know the details of the received status code and response headers.",
   'output': 'The request to https://httpbin.org/status/404 was successful and the response contains the expected status code of 404 and the following response headers: Content-Type: text/html; charset=UTF-8, Content-Length: 232, Server: gunicorn/19.9.0, Date: Wed, 11 Aug 2021 17:54:00 GMT.',
   'Final Thought': 'The request was successful and the response contains the expected status code of 404 and the response headers.',
   'intermediate_steps': [[['simulateStatusCode',
      '{"url": "https://httpbin.org/status/404", "statusCode": 404}',
      ' I need to use the simulateStatusCode tool to send a request to the Httpbin API\'s status code simulation endpoint.\nAction: simulateStatusCode\nAction Input: {"url": "https://httpbin.org/status/404", "statusCode": 404}'],
     'Status Code: 200. Response: {"response":{"status_code":404,"headers":{"Content-Type":"text/html; charset=UTF-8","Content-Length":"232","Server":"gunicorn/19.9.0","Date":"Wed, 11 Aug 2021 17:54:00 GMT"},"body":"<html>\\n<head>\\n    <title>404 Not Found</title>\\n</head>\\n<body>\\n    <h1>404 Not Found</h1>\\n    The resource could not be found.\\n</body>\\n</html>"}}']]},
  {'input': 'I need to test how my app handles a "PATCH" request. Can you send a PATCH request to https://httpbin.org/patch with the data \'{"field": "value"}\' and tell me the response?',
   'output': 'The PATCH request to https://httpbin.org/patch with the data \'{"field": "value"}\' was successful, with a status code of 200. The response from the request was: {"response":"{\\n  \\"response\\": {\\n    \\"status_code\\": 200,\\n    \\"headers\\": {\\n      \\"Host\\": \\"httpbin.org\\",\\n      \\"Content-Type\\": \\"application/json\\",\\n      \\"Content-Length\\": \\"365\\",\\n      \\"Access-Control-Allow-Origin\\": \\"*\\",\\n      \\"Access-Control-Allow-Credentials\\": \\"true\\",\\n      \\"Connection\\": \\"keep-alive\\"\\n    },\\n    \\"body\\": \\"{\\\\n  \\\\\\"args\\\\\\": {}, \\\\n  \\\\\\"data\\\\\\": \\\\\\"{\\\\\'field\\\\\': \\\\\'value\\\\\'}\\\\\\", \\\\n  \\\\\\"files\\\\\\": {}, \\\\n  \\\\\\"form\\\\\\": {}, \\\\n  \\\\\\"headers\\\\\\": {\\\\n    \\\\\\"Content-',
   'Final Thought': 'The response from the PATCH request was successful, with a status code of 200.',
   'intermediate_steps': [[['sendHttpRequest',
      '{"method": "PATCH", "url": "https://httpbin.org/patch", "headers": {}, "data": {"field": "value"}}',

In [ ]:
SYSTEM_PROMPT = """You are an intelligent AI agent that answers questions by reasoning step-by-step.

You have access to the following tools:
{tool_docs}

Use this STRICT format for reasoning — output a JSON block:
{{"thought": "...", "action": "...", "action_input": {{"key": "value"}}}}

If you have enough information, output a final JSON block:
{{"thought": "...", "final_answer": "..."}}

RULES:
- STOP generating immediately after closing the JSON block.
- action_input MUST be a valid JSON object (double-quoted keys, no trailing commas).
- Only call tools listed above; never fabricate tool names or results.
- Always output valid JSON — no trailing commas, no single quotes.
- Use the final_answer JSON format (with "thought" and "final_answer" keys, omitting "action" and "action_input") only when you have gathered enough information to fully answer the user's question."""

In [ ]:
def parse_output_trajectory_reasoning(intermediate_step):

    step = {}
    tool_name, action_input, thought_action = intermediate_step[0]

    step['thought'] = thought_action
    step['action'] = tool_name
    step['action_input'] = action_input

    return json.dumps(step)

In [ ]:
def parse_output_trajectory_answer(instance):

    step = {}

    final_thought = instance.get("Final Thought", "")
    output = instance.get("output", "")

    step['thought'] = final_thought
    step['final_answer'] = output

    return json.dumps(step)

In [ ]:
def make_training_example(tool, instance, step):

    history = []
    intermediate_steps_list = instance.get("intermediate_steps", [])
    number_of_intermediate_steps = len(intermediate_steps_list)

    for idx in range(step):
      ho_input = intermediate_steps_list[idx][0]
      observation = intermediate_steps_list[idx][1]
      history.append({'action': ho_input[0], 'action_input': ho_input[1], 'observation': observation})

    system_text = SYSTEM_PROMPT.format(tool_docs=tool.get("NLDocumentation", "").strip())

    user_query = f"Query: {instance.get("input", "").strip()}\nHistory: {json.dumps(history)}"

    if step<number_of_intermediate_steps:
      trajectory = parse_output_trajectory_reasoning(intermediate_steps_list[step]).strip()

    else:
      trajectory = parse_output_trajectory_answer(instance).strip()


    return [
        {"role": "system", "content": system_text},
        {"role": "user", "content": user_query},
        {"role": "assistant", "content": trajectory},
    ]

In [ ]:
train_texts = []

for tool in raw_train:
    for instance in (tool.get("Instances", [])):
      for step in range(len(instance.get("intermediate_steps", []))+1):
        ex = make_training_example(tool, instance, step)
        if ex:
            train_texts.append({"messages": ex})

In [ ]:
print(train_texts[1]["messages"][1]["content"])

Query: I'm troubleshooting some requests, so can you help me send a POST request to https://httpbin.org/post with the header "Content-Type: application/json" and the data '{"name": "John Doe", "email": "john.doe@example.com"}'? Let me know the response details.
History: [{"action": "sendHttpRequest", "action_input": "{\"method\": \"POST\", \"url\": \"https://httpbin.org/post\", \"headers\": {\"Content-Type\": \"application/json\"}, \"data\": {\"name\": \"John Doe\", \"email\": \"john.doe@example.com\"}}", "observation": "Status Code: 200. Response: {\"response\":{\"status_code\":200,\"headers\":{\"Content-Type\":\"application/json\"},\"body\":\"{\\\"args\\\":{\\\"method\\\":\\\"POST\\\",\\\"url\\\":\\\"https://httpbin.org/post\\\",\\\"headers\\\":{\\\"'Content-Type'\\\":\\\"'application/json'\\\"},\\\"data\\\":{\\\"'name'\\\":\\\"'John Doe'\\\",\\\"'email'\\\":\\\"'john.doe@example.com'\\\"}},\\\"data\\\":\\\"\\\",\\\"files\\\":{},\\\"form\\\":{},\\\"headers\\\":{\\\"Accept\\\":\\\"*/*\\\",\\\"Content-Length\\\":\\\"48\\\",\\\"Content-Type\\\":\\\"application/x-www-form-urlencoded\\\",\\\"Host\\\":\\\"httpbin.org\\\",\\\"User-Agent\\\":\\\"curl/7.68.0\\\"},\\\"json\\\":{\\\"'name'\\\":\\\"'John Doe'\\\",\\\"'email'\\\":\\\"'john.doe@example.com'\\\"},\\\"method\\\":\\\"POST\\\",\\\"origin\\\":\\\"127.0.0.1\\\",\\\"url\\\":\\\"https://httpbin.org/post\\\"}\"}}"}]

In [ ]:
len(train_texts)

11970

In [ ]:
hf_dataset = Dataset.from_list(train_texts).shuffle(seed=42)
split = hf_dataset.train_test_split(test_size=0.2, seed=42)

train_ds, val_ds = split["train"], split["test"]

In [ ]:
len(train_ds), len(val_ds)

(9576, 2394)

In [ ]:
# cache_dir = "/content/drive/MyDrive/hf_cache"
# os.makedirs(cache_dir, exist_ok=True)

# os.environ["HF_HOME"] = cache_dir
# os.environ["TRANSFORMERS_CACHE"] = cache_dir

In [ ]:
model_kwargs = dict(
    dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True
)

In [ ]:
model_kwargs["quantization_config"] = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_compute_dtype=model_kwargs['dtype'],
    bnb_4bit_quant_storage=model_kwargs['dtype'],
)

In [ ]:
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, **model_kwargs)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/10.2G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/1951 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/208 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/32.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

In [ ]:
peft_config = LoraConfig(
    task_type="CAUSAL_LM",
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    bias="none",
    target_modules="all-linear"
)

In [ ]:
args = SFTConfig(
    output_dir="gemma-4-ToolAlpaca-FineTune-C",
    max_length=MAX_SEQ_LEN,
    num_train_epochs=1,
    per_device_train_batch_size=2,
    optim="paged_adamw_8bit",
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    learning_rate=5e-5,
    fp16=False,
    bf16=True,
    max_grad_norm=0.3,
    lr_scheduler_type="constant",
    push_to_hub=True,
    report_to="tensorboard",
    dataloader_num_workers=2,
    packing = False,
    gradient_accumulation_steps=4,
    dataset_kwargs={
        "add_special_tokens": False,
        "append_concat_token": False
    },
    gradient_checkpointing=False,
)

In [ ]:
trainer = SFTTrainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    peft_config=peft_config,
    processing_class=tokenizer,
)

Tokenizing train dataset:   0%|          | 0/9576 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/2394 [00:00<?, ? examples/s]

In [ ]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 1, 'bos_token_id': 2, 'pad_token_id': 0}.

TrainOutput(global_step=1197, training_loss=0.3381721715978911, metrics={'train_runtime': 15368.8549, 'train_samples_per_second': 0.623, 'train_steps_per_second': 0.078, 'total_flos': 3.474665697588019e+16, 'train_loss': 0.3381721715978911})

In [ ]:
trainer.save_model()

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...eTune-C/training_args.bin: 100%|##########| 5.78kB / 5.78kB

  ...47530.e77c384019a8.1160.0: 100%|##########| 56.0kB / 56.0kB

  ...adapter_model.safetensors: 100%|##########| 19.1MB / 19.1MB

  ...FineTune-C/tokenizer.json: 100%|##########| 32.2MB / 32.2MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

In [ ]:
tokenizer.save_pretrained("gemma-4-ToolAlpaca-FineTune-C")

('gemma-4-ToolAlpaca-FineTune-C/tokenizer_config.json',
 'gemma-4-ToolAlpaca-FineTune-C/chat_template.jinja',
 'gemma-4-ToolAlpaca-FineTune-C/tokenizer.json')

In [ ]:
torch.cuda.empty_cache()

In [ ]:
trainer.args.per_device_eval_batch_size = 1
trainer.args.eval_accumulation_steps = 1
trainer.args.prediction_loss_only = True

metrics = trainer.evaluate()
print(metrics)

{'eval_loss': 0.047019220888614655}

In [ ]:
from google.colab import runtime
runtime.unassign()